---
version: "3.9"
services:
  minecraft:
    build: .
    cpus: 2
    # mem_reservation: 1G
    # mem_limit: 4G
    environment:
      - DEFAULT_OP=dlord69
      - MINECRAFT_EULA=true
      - MINECRAFT_OPTS=-server -Xmx2G -Xlog:gc -XshowSettings:vm -XX:+PrintFlagsFinal -XX:+UseG1GC -XX:MaxGCPauseMillis=50 -XX:+AlwaysPreTouch -XX:+DisableExplicitGC
    volumes:
      - minecraft-data:/opt/minecraft
volumes:
  minecraft-data:
